
if exist('eigen/Eigen/Dense','file')
    disp('compiling ...');
    mex -I./../matlab-bindings/eigen ...
        ../src/Meta.cpp ../src/ISolver.cpp ...
        ../src/GradientDescentSolver.cpp ...
        ../src/NewtonDescentSolver.cpp ...
        ../src/BfgsSolver.cpp ...
        ../src/LbfgsSolver.cpp   ...
        ../src/LbfgsbSolver.cpp ...
        cppsolver.cpp  ...
        CXXFLAGS="\$CXXFLAGS -std=c++11" ...
        -output cppsolver;
else
    disp('Eigen is missing');
end


