
if exist('eigen/Eigen/Dense','file')
    disp('compiling ...');
    mex -I./../matlab-bindings/eigen ...
        ../src/Meta.cpp ../src/ISolver.cpp ...
        ../src/GradientDescentSolver.cpp ...
        ../src/BfgsSolver.cpp ...
        ../src/LbfgsSolver.cpp cppsolver.cpp  ...
        -output cppsolver;
else
    
end


