---
kind: pipeline
name: Build

platform:
  os: linux
  arch: amd64

steps:

- name: code-format
  pull: never
  image: patwie/clang-format:latest
  commands:
  - python /run-clang-format.py --clang-format-executable /clang-format/clang-format11 -r . --style Google

- name: build
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run simple

- name: verify
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run verify

---
kind: signature
hmac: 813cba34379e693f9d5d69e896df19d5a57026a07238e5d770044eab7d1e2aae

...
