---
kind: pipeline
name: Build

platform:
  os: linux
  arch: amd64

steps:

- name: code-format
  pull: never
  image: patwie/lint:latest
  commands:
  - run-clang-format --clang-format-executable /usr/local/bin/clang-format11 -r . --style Google

- name: code-lint
  pull: never
  image: patwie/lint:latest
  commands:
  - 'cpplint --extensions=h,hpp,c,cpp,cc,cu,hh,ipp --filter="-build/include_order" --recursive include > reviewdog -efm="%f:%l: %m" -name="cpplint" -reporter="local"'

- name: build
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run simple

- name: verify
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run verify

---
kind: signature
hmac: 07789a1cc8328b0bba26d1b64a6ffa246cee4395e163a5a5f1b77c738f31cb8a

...
