---
kind: pipeline
name: Build

platform:
  os: linux
  arch: amd64

steps:

- name: build
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run simple

- name: verify
  pull: never
  image: cppnumericalsolver2
  commands:
  - /root/bin/bazel run verify


---
kind: signature
hmac: f1d4c1c1842c1b8f69c2083023db3044510eed3a52f716c464b7a2e2950a3063

...
