cc_library(
    name = "cppoptlib",
    hdrs = glob([
        "cppoptlib/*.h",
        "cppoptlib/solver/*.h",
        "cppoptlib/linesearch/*.h",
        "cppoptlib/utils/*.h",
    ]),
    includes = ["."],
    visibility = ["//visibility:public"],
)
